# Generated by Django 2.0.1 on 2019-09-22 12:43

from django.db import migrations, models
import django.db.models.deletion


def create_topics(apps, schema_editor):
    Topics = apps.get_model('classroom', 'Topics')
    Topics.objects.create(topic_name='test_topic_1', subject_id=1)
    Topics.objects.create(topic_name='test_topic_2', subject_id=2)
    Topics.objects.create(topic_name='test_topic_3', subject_id=3)
    Topics.objects.create(topic_name='test_topic_4', subject_id=4)
    Topics.objects.create(topic_name='test_topic_5', subject_id=1)
    Topics.objects.create(topic_name='test_topic_6', subject_id=2)
    Topics.objects.create(topic_name='test_topic_7', subject_id=3)
    Topics.objects.create(topic_name='test_topic_8', subject_id=4)


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20190922_1715'),
    ]

    operations = [migrations.RunPython(create_topics),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='classroom.Topics'),
        ),
    ]


